[package]
name = "print-core"
version = "0.1.2"
authors = ["lhojun"]
edition = "2021"
license = "MIT"
description = "Rust Print Core for Windows/macOS"
repository = "https://github.com/lhojun/print-core"
[dependencies]